name: Discord Webhook - New Release

on:
  release:
    types: [published]

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          REPO_NAME: ${{ github.repository }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
          THUMBNAIL_URL: "https://i.imgur.com/zsRT2cW.png"  # Thumbnail image
          LOGO_URL: "https://i.imgur.com/u5mzCKD.png"  # KCDMOD Logo
        run: |
          CHANGELOG=$(echo "$RELEASE_BODY" | head -n 10) # Get first 10 lines of the changelog if available
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "📢 New KCDMOD update available!",
                   "description": "**'"$RELEASE_NAME"'** (`'"$RELEASE_TAG"'`)\n\n🔄 **Restart the launcher to update!**\n\n'"$CHANGELOG"'",
                   "color": 5814783,
                   "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",
                   "footer": { "text": "GitHub Releases" },
                   "thumbnail": { "url": "'"$THUMBNAIL_URL"'" },
                   "author": {
                     "name": "KCDMOD",
                     "icon_url": "'"$LOGO_URL"'"
                   }
                 }]
               }' \
               "$DISCORD_WEBHOOK"
